import { z } from 'zod'

export const productFormSchema = z.object({
  name: z.string().min(1, 'Naziv je obavezan'),
  slug: z.string().min(1, 'Slug je obavezan'),
  description: z.string().nullish(),
  price: z.number().min(0, 'Cena je obavezna'),
  compareAtPrice: z.number().nullish(),
  currency: z.enum(['RSD', 'EUR', 'USD']),
  images: z.array(z.string()),
  unit: z.enum([
    'piece',
    'kg',
    'g',
    'l',
    'ml',
    'pcs',
    'box',
    'bag',
    'jar',
    'tube',
    'bottle',
    'can',
    'pack',
    'box',
    'bag',
    'jar',
    'tube',
    'bottle',
    'can',
    'pack',
  ]),
  trackInventory: z.boolean(),
  stockQty: z.number().nullish(),
  lowStockThreshold: z.number().nullish(),
  sku: z.string().min(1, 'SKU je obavezan'),
  tags: z.array(z.string()),
  attributes: z.record(z.string(), z.string()),
  seoTitle: z.string().nullish(),
  seoDescription: z.string().nullish(),
  status: z.enum(['draft', 'published', 'out_of_stock', 'archived']),
  publishedAt: z.date().nullish(),
  archivedAt: z.date().nullish(),
})

export type ProductFormSchema = z.infer<typeof productFormSchema>

export const defaultValues: ProductFormSchema = {
  name: '',
  slug: '',
  description: '',
  price: 0,
  compareAtPrice: 0,
  currency: 'RSD',
  images: [],
  unit: 'piece',
  trackInventory: true,
  stockQty: 0,
  lowStockThreshold: 0,
  sku: '',
  tags: [],
  attributes: {},
  seoTitle: '',
  seoDescription: '',
  status: 'draft',
  publishedAt: null,
  archivedAt: null,
}
