/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as PrivateRouteRouteImport } from './routes/_private/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicGoodbyeRouteRouteImport } from './routes/_public/goodbye/route'
import { Route as PublicAuthRouteRouteImport } from './routes/_public/auth/route'
import { Route as PrivateSellerRouteRouteImport } from './routes/_private/seller/route'
import { Route as PrivateBuyerRouteRouteImport } from './routes/_private/buyer/route'
import { Route as PrivateAdminRouteRouteImport } from './routes/_private/admin/route'
import { Route as PublicSellerApplyIndexRouteImport } from './routes/_public/seller-apply/index'
import { Route as PrivateAccountIndexRouteImport } from './routes/_private/account/index'
import { Route as AuthResetPasswordIndexRouteImport } from './routes/_auth/reset-password/index'
import { Route as AuthRegisterIndexRouteImport } from './routes/_auth/register/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as AuthForgotPasswordIndexRouteImport } from './routes/_auth/forgot-password/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as PrivateSellerProductsIndexRouteImport } from './routes/_private/seller/products/index'
import { Route as PrivateSellerInfoIndexRouteImport } from './routes/_private/seller/info/index'
import { Route as PrivateBuyerOrdersIndexRouteImport } from './routes/_private/buyer/orders/index'
import { Route as PrivateAdminUsersIndexRouteImport } from './routes/_private/admin/users/index'
import { Route as PrivateAdminSellersIndexRouteImport } from './routes/_private/admin/sellers/index'
import { Route as PrivateAdminCategoriesIndexRouteImport } from './routes/_private/admin/categories/index'
import { Route as PrivateAdminBannersIndexRouteImport } from './routes/_private/admin/banners/index'
import { Route as PrivateAccountOrdersIndexRouteImport } from './routes/_private/account/orders/index'
import { Route as ApiAuthDeleteUserCallbackRouteImport } from './routes/api/auth/delete-user/callback'
import { Route as PrivateSellerProductsCreateIndexRouteImport } from './routes/_private/seller/products/create/index'
import { Route as PrivateAdminBannersCreateIndexRouteImport } from './routes/_private/admin/banners/create/index'
import { Route as PrivateSellerProductsPreviewProductIdRouteImport } from './routes/_private/seller/products/preview/$productId'
import { Route as PrivateSellerProductsEditProductIdRouteImport } from './routes/_private/seller/products/edit/$productId'
import { Route as PrivateAdminBannersEditBannerIdRouteImport } from './routes/_private/admin/banners/edit/$bannerId'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRouteRoute = PrivateRouteRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicGoodbyeRouteRoute = PublicGoodbyeRouteRouteImport.update({
  id: '/goodbye',
  path: '/goodbye',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicAuthRouteRoute = PublicAuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PrivateSellerRouteRoute = PrivateSellerRouteRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateBuyerRouteRoute = PrivateBuyerRouteRouteImport.update({
  id: '/buyer',
  path: '/buyer',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateAdminRouteRoute = PrivateAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PublicSellerApplyIndexRoute = PublicSellerApplyIndexRouteImport.update({
  id: '/seller-apply/',
  path: '/seller-apply/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PrivateAccountIndexRoute = PrivateAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const AuthResetPasswordIndexRoute = AuthResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterIndexRoute = AuthRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordIndexRoute = AuthForgotPasswordIndexRouteImport.update({
  id: '/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateSellerProductsIndexRoute =
  PrivateSellerProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => PrivateSellerRouteRoute,
  } as any)
const PrivateSellerInfoIndexRoute = PrivateSellerInfoIndexRouteImport.update({
  id: '/info/',
  path: '/info/',
  getParentRoute: () => PrivateSellerRouteRoute,
} as any)
const PrivateBuyerOrdersIndexRoute = PrivateBuyerOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => PrivateBuyerRouteRoute,
} as any)
const PrivateAdminUsersIndexRoute = PrivateAdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => PrivateAdminRouteRoute,
} as any)
const PrivateAdminSellersIndexRoute =
  PrivateAdminSellersIndexRouteImport.update({
    id: '/sellers/',
    path: '/sellers/',
    getParentRoute: () => PrivateAdminRouteRoute,
  } as any)
const PrivateAdminCategoriesIndexRoute =
  PrivateAdminCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => PrivateAdminRouteRoute,
  } as any)
const PrivateAdminBannersIndexRoute =
  PrivateAdminBannersIndexRouteImport.update({
    id: '/banners/',
    path: '/banners/',
    getParentRoute: () => PrivateAdminRouteRoute,
  } as any)
const PrivateAccountOrdersIndexRoute =
  PrivateAccountOrdersIndexRouteImport.update({
    id: '/account/orders/',
    path: '/account/orders/',
    getParentRoute: () => PrivateRouteRoute,
  } as any)
const ApiAuthDeleteUserCallbackRoute =
  ApiAuthDeleteUserCallbackRouteImport.update({
    id: '/api/auth/delete-user/callback',
    path: '/api/auth/delete-user/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrivateSellerProductsCreateIndexRoute =
  PrivateSellerProductsCreateIndexRouteImport.update({
    id: '/products/create/',
    path: '/products/create/',
    getParentRoute: () => PrivateSellerRouteRoute,
  } as any)
const PrivateAdminBannersCreateIndexRoute =
  PrivateAdminBannersCreateIndexRouteImport.update({
    id: '/banners/create/',
    path: '/banners/create/',
    getParentRoute: () => PrivateAdminRouteRoute,
  } as any)
const PrivateSellerProductsPreviewProductIdRoute =
  PrivateSellerProductsPreviewProductIdRouteImport.update({
    id: '/products/preview/$productId',
    path: '/products/preview/$productId',
    getParentRoute: () => PrivateSellerRouteRoute,
  } as any)
const PrivateSellerProductsEditProductIdRoute =
  PrivateSellerProductsEditProductIdRouteImport.update({
    id: '/products/edit/$productId',
    path: '/products/edit/$productId',
    getParentRoute: () => PrivateSellerRouteRoute,
  } as any)
const PrivateAdminBannersEditBannerIdRoute =
  PrivateAdminBannersEditBannerIdRouteImport.update({
    id: '/banners/edit/$bannerId',
    path: '/banners/edit/$bannerId',
    getParentRoute: () => PrivateAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof PrivateAdminRouteRouteWithChildren
  '/buyer': typeof PrivateBuyerRouteRouteWithChildren
  '/seller': typeof PrivateSellerRouteRouteWithChildren
  '/auth': typeof PublicAuthRouteRoute
  '/goodbye': typeof PublicGoodbyeRouteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/forgot-password/': typeof AuthForgotPasswordIndexRoute
  '/login/': typeof AuthLoginIndexRoute
  '/register/': typeof AuthRegisterIndexRoute
  '/reset-password/': typeof AuthResetPasswordIndexRoute
  '/account/': typeof PrivateAccountIndexRoute
  '/seller-apply/': typeof PublicSellerApplyIndexRoute
  '/api/auth/delete-user/callback': typeof ApiAuthDeleteUserCallbackRoute
  '/account/orders/': typeof PrivateAccountOrdersIndexRoute
  '/admin/banners/': typeof PrivateAdminBannersIndexRoute
  '/admin/categories/': typeof PrivateAdminCategoriesIndexRoute
  '/admin/sellers/': typeof PrivateAdminSellersIndexRoute
  '/admin/users/': typeof PrivateAdminUsersIndexRoute
  '/buyer/orders/': typeof PrivateBuyerOrdersIndexRoute
  '/seller/info/': typeof PrivateSellerInfoIndexRoute
  '/seller/products/': typeof PrivateSellerProductsIndexRoute
  '/admin/banners/edit/$bannerId': typeof PrivateAdminBannersEditBannerIdRoute
  '/seller/products/edit/$productId': typeof PrivateSellerProductsEditProductIdRoute
  '/seller/products/preview/$productId': typeof PrivateSellerProductsPreviewProductIdRoute
  '/admin/banners/create/': typeof PrivateAdminBannersCreateIndexRoute
  '/seller/products/create/': typeof PrivateSellerProductsCreateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/admin': typeof PrivateAdminRouteRouteWithChildren
  '/buyer': typeof PrivateBuyerRouteRouteWithChildren
  '/seller': typeof PrivateSellerRouteRouteWithChildren
  '/auth': typeof PublicAuthRouteRoute
  '/goodbye': typeof PublicGoodbyeRouteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/forgot-password': typeof AuthForgotPasswordIndexRoute
  '/login': typeof AuthLoginIndexRoute
  '/register': typeof AuthRegisterIndexRoute
  '/reset-password': typeof AuthResetPasswordIndexRoute
  '/account': typeof PrivateAccountIndexRoute
  '/seller-apply': typeof PublicSellerApplyIndexRoute
  '/api/auth/delete-user/callback': typeof ApiAuthDeleteUserCallbackRoute
  '/account/orders': typeof PrivateAccountOrdersIndexRoute
  '/admin/banners': typeof PrivateAdminBannersIndexRoute
  '/admin/categories': typeof PrivateAdminCategoriesIndexRoute
  '/admin/sellers': typeof PrivateAdminSellersIndexRoute
  '/admin/users': typeof PrivateAdminUsersIndexRoute
  '/buyer/orders': typeof PrivateBuyerOrdersIndexRoute
  '/seller/info': typeof PrivateSellerInfoIndexRoute
  '/seller/products': typeof PrivateSellerProductsIndexRoute
  '/admin/banners/edit/$bannerId': typeof PrivateAdminBannersEditBannerIdRoute
  '/seller/products/edit/$productId': typeof PrivateSellerProductsEditProductIdRoute
  '/seller/products/preview/$productId': typeof PrivateSellerProductsPreviewProductIdRoute
  '/admin/banners/create': typeof PrivateAdminBannersCreateIndexRoute
  '/seller/products/create': typeof PrivateSellerProductsCreateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_private': typeof PrivateRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_private/admin': typeof PrivateAdminRouteRouteWithChildren
  '/_private/buyer': typeof PrivateBuyerRouteRouteWithChildren
  '/_private/seller': typeof PrivateSellerRouteRouteWithChildren
  '/_public/auth': typeof PublicAuthRouteRoute
  '/_public/goodbye': typeof PublicGoodbyeRouteRoute
  '/_public/': typeof PublicIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/forgot-password/': typeof AuthForgotPasswordIndexRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_auth/register/': typeof AuthRegisterIndexRoute
  '/_auth/reset-password/': typeof AuthResetPasswordIndexRoute
  '/_private/account/': typeof PrivateAccountIndexRoute
  '/_public/seller-apply/': typeof PublicSellerApplyIndexRoute
  '/api/auth/delete-user/callback': typeof ApiAuthDeleteUserCallbackRoute
  '/_private/account/orders/': typeof PrivateAccountOrdersIndexRoute
  '/_private/admin/banners/': typeof PrivateAdminBannersIndexRoute
  '/_private/admin/categories/': typeof PrivateAdminCategoriesIndexRoute
  '/_private/admin/sellers/': typeof PrivateAdminSellersIndexRoute
  '/_private/admin/users/': typeof PrivateAdminUsersIndexRoute
  '/_private/buyer/orders/': typeof PrivateBuyerOrdersIndexRoute
  '/_private/seller/info/': typeof PrivateSellerInfoIndexRoute
  '/_private/seller/products/': typeof PrivateSellerProductsIndexRoute
  '/_private/admin/banners/edit/$bannerId': typeof PrivateAdminBannersEditBannerIdRoute
  '/_private/seller/products/edit/$productId': typeof PrivateSellerProductsEditProductIdRoute
  '/_private/seller/products/preview/$productId': typeof PrivateSellerProductsPreviewProductIdRoute
  '/_private/admin/banners/create/': typeof PrivateAdminBannersCreateIndexRoute
  '/_private/seller/products/create/': typeof PrivateSellerProductsCreateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/buyer'
    | '/seller'
    | '/auth'
    | '/goodbye'
    | '/api/auth/$'
    | '/forgot-password/'
    | '/login/'
    | '/register/'
    | '/reset-password/'
    | '/account/'
    | '/seller-apply/'
    | '/api/auth/delete-user/callback'
    | '/account/orders/'
    | '/admin/banners/'
    | '/admin/categories/'
    | '/admin/sellers/'
    | '/admin/users/'
    | '/buyer/orders/'
    | '/seller/info/'
    | '/seller/products/'
    | '/admin/banners/edit/$bannerId'
    | '/seller/products/edit/$productId'
    | '/seller/products/preview/$productId'
    | '/admin/banners/create/'
    | '/seller/products/create/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/buyer'
    | '/seller'
    | '/auth'
    | '/goodbye'
    | '/api/auth/$'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/account'
    | '/seller-apply'
    | '/api/auth/delete-user/callback'
    | '/account/orders'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/sellers'
    | '/admin/users'
    | '/buyer/orders'
    | '/seller/info'
    | '/seller/products'
    | '/admin/banners/edit/$bannerId'
    | '/seller/products/edit/$productId'
    | '/seller/products/preview/$productId'
    | '/admin/banners/create'
    | '/seller/products/create'
  id:
    | '__root__'
    | '/_auth'
    | '/_private'
    | '/_public'
    | '/_private/admin'
    | '/_private/buyer'
    | '/_private/seller'
    | '/_public/auth'
    | '/_public/goodbye'
    | '/_public/'
    | '/api/auth/$'
    | '/_auth/forgot-password/'
    | '/_auth/login/'
    | '/_auth/register/'
    | '/_auth/reset-password/'
    | '/_private/account/'
    | '/_public/seller-apply/'
    | '/api/auth/delete-user/callback'
    | '/_private/account/orders/'
    | '/_private/admin/banners/'
    | '/_private/admin/categories/'
    | '/_private/admin/sellers/'
    | '/_private/admin/users/'
    | '/_private/buyer/orders/'
    | '/_private/seller/info/'
    | '/_private/seller/products/'
    | '/_private/admin/banners/edit/$bannerId'
    | '/_private/seller/products/edit/$productId'
    | '/_private/seller/products/preview/$productId'
    | '/_private/admin/banners/create/'
    | '/_private/seller/products/create/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  PrivateRouteRoute: typeof PrivateRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAuthDeleteUserCallbackRoute: typeof ApiAuthDeleteUserCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/goodbye': {
      id: '/_public/goodbye'
      path: '/goodbye'
      fullPath: '/goodbye'
      preLoaderRoute: typeof PublicGoodbyeRouteRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/auth': {
      id: '/_public/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof PublicAuthRouteRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_private/seller': {
      id: '/_private/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof PrivateSellerRouteRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/buyer': {
      id: '/_private/buyer'
      path: '/buyer'
      fullPath: '/buyer'
      preLoaderRoute: typeof PrivateBuyerRouteRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/admin': {
      id: '/_private/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof PrivateAdminRouteRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_public/seller-apply/': {
      id: '/_public/seller-apply/'
      path: '/seller-apply'
      fullPath: '/seller-apply/'
      preLoaderRoute: typeof PublicSellerApplyIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_private/account/': {
      id: '/_private/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof PrivateAccountIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_auth/reset-password/': {
      id: '/_auth/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof AuthResetPasswordIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/register/': {
      id: '/_auth/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof AuthRegisterIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgot-password/': {
      id: '/_auth/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password/'
      preLoaderRoute: typeof AuthForgotPasswordIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/seller/products/': {
      id: '/_private/seller/products/'
      path: '/products'
      fullPath: '/seller/products/'
      preLoaderRoute: typeof PrivateSellerProductsIndexRouteImport
      parentRoute: typeof PrivateSellerRouteRoute
    }
    '/_private/seller/info/': {
      id: '/_private/seller/info/'
      path: '/info'
      fullPath: '/seller/info/'
      preLoaderRoute: typeof PrivateSellerInfoIndexRouteImport
      parentRoute: typeof PrivateSellerRouteRoute
    }
    '/_private/buyer/orders/': {
      id: '/_private/buyer/orders/'
      path: '/orders'
      fullPath: '/buyer/orders/'
      preLoaderRoute: typeof PrivateBuyerOrdersIndexRouteImport
      parentRoute: typeof PrivateBuyerRouteRoute
    }
    '/_private/admin/users/': {
      id: '/_private/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof PrivateAdminUsersIndexRouteImport
      parentRoute: typeof PrivateAdminRouteRoute
    }
    '/_private/admin/sellers/': {
      id: '/_private/admin/sellers/'
      path: '/sellers'
      fullPath: '/admin/sellers/'
      preLoaderRoute: typeof PrivateAdminSellersIndexRouteImport
      parentRoute: typeof PrivateAdminRouteRoute
    }
    '/_private/admin/categories/': {
      id: '/_private/admin/categories/'
      path: '/categories'
      fullPath: '/admin/categories/'
      preLoaderRoute: typeof PrivateAdminCategoriesIndexRouteImport
      parentRoute: typeof PrivateAdminRouteRoute
    }
    '/_private/admin/banners/': {
      id: '/_private/admin/banners/'
      path: '/banners'
      fullPath: '/admin/banners/'
      preLoaderRoute: typeof PrivateAdminBannersIndexRouteImport
      parentRoute: typeof PrivateAdminRouteRoute
    }
    '/_private/account/orders/': {
      id: '/_private/account/orders/'
      path: '/account/orders'
      fullPath: '/account/orders/'
      preLoaderRoute: typeof PrivateAccountOrdersIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/api/auth/delete-user/callback': {
      id: '/api/auth/delete-user/callback'
      path: '/api/auth/delete-user/callback'
      fullPath: '/api/auth/delete-user/callback'
      preLoaderRoute: typeof ApiAuthDeleteUserCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/seller/products/create/': {
      id: '/_private/seller/products/create/'
      path: '/products/create'
      fullPath: '/seller/products/create/'
      preLoaderRoute: typeof PrivateSellerProductsCreateIndexRouteImport
      parentRoute: typeof PrivateSellerRouteRoute
    }
    '/_private/admin/banners/create/': {
      id: '/_private/admin/banners/create/'
      path: '/banners/create'
      fullPath: '/admin/banners/create/'
      preLoaderRoute: typeof PrivateAdminBannersCreateIndexRouteImport
      parentRoute: typeof PrivateAdminRouteRoute
    }
    '/_private/seller/products/preview/$productId': {
      id: '/_private/seller/products/preview/$productId'
      path: '/products/preview/$productId'
      fullPath: '/seller/products/preview/$productId'
      preLoaderRoute: typeof PrivateSellerProductsPreviewProductIdRouteImport
      parentRoute: typeof PrivateSellerRouteRoute
    }
    '/_private/seller/products/edit/$productId': {
      id: '/_private/seller/products/edit/$productId'
      path: '/products/edit/$productId'
      fullPath: '/seller/products/edit/$productId'
      preLoaderRoute: typeof PrivateSellerProductsEditProductIdRouteImport
      parentRoute: typeof PrivateSellerRouteRoute
    }
    '/_private/admin/banners/edit/$bannerId': {
      id: '/_private/admin/banners/edit/$bannerId'
      path: '/banners/edit/$bannerId'
      fullPath: '/admin/banners/edit/$bannerId'
      preLoaderRoute: typeof PrivateAdminBannersEditBannerIdRouteImport
      parentRoute: typeof PrivateAdminRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordIndexRoute: typeof AuthForgotPasswordIndexRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
  AuthResetPasswordIndexRoute: typeof AuthResetPasswordIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordIndexRoute: AuthForgotPasswordIndexRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
  AuthResetPasswordIndexRoute: AuthResetPasswordIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface PrivateAdminRouteRouteChildren {
  PrivateAdminBannersIndexRoute: typeof PrivateAdminBannersIndexRoute
  PrivateAdminCategoriesIndexRoute: typeof PrivateAdminCategoriesIndexRoute
  PrivateAdminSellersIndexRoute: typeof PrivateAdminSellersIndexRoute
  PrivateAdminUsersIndexRoute: typeof PrivateAdminUsersIndexRoute
  PrivateAdminBannersEditBannerIdRoute: typeof PrivateAdminBannersEditBannerIdRoute
  PrivateAdminBannersCreateIndexRoute: typeof PrivateAdminBannersCreateIndexRoute
}

const PrivateAdminRouteRouteChildren: PrivateAdminRouteRouteChildren = {
  PrivateAdminBannersIndexRoute: PrivateAdminBannersIndexRoute,
  PrivateAdminCategoriesIndexRoute: PrivateAdminCategoriesIndexRoute,
  PrivateAdminSellersIndexRoute: PrivateAdminSellersIndexRoute,
  PrivateAdminUsersIndexRoute: PrivateAdminUsersIndexRoute,
  PrivateAdminBannersEditBannerIdRoute: PrivateAdminBannersEditBannerIdRoute,
  PrivateAdminBannersCreateIndexRoute: PrivateAdminBannersCreateIndexRoute,
}

const PrivateAdminRouteRouteWithChildren =
  PrivateAdminRouteRoute._addFileChildren(PrivateAdminRouteRouteChildren)

interface PrivateBuyerRouteRouteChildren {
  PrivateBuyerOrdersIndexRoute: typeof PrivateBuyerOrdersIndexRoute
}

const PrivateBuyerRouteRouteChildren: PrivateBuyerRouteRouteChildren = {
  PrivateBuyerOrdersIndexRoute: PrivateBuyerOrdersIndexRoute,
}

const PrivateBuyerRouteRouteWithChildren =
  PrivateBuyerRouteRoute._addFileChildren(PrivateBuyerRouteRouteChildren)

interface PrivateSellerRouteRouteChildren {
  PrivateSellerInfoIndexRoute: typeof PrivateSellerInfoIndexRoute
  PrivateSellerProductsIndexRoute: typeof PrivateSellerProductsIndexRoute
  PrivateSellerProductsEditProductIdRoute: typeof PrivateSellerProductsEditProductIdRoute
  PrivateSellerProductsPreviewProductIdRoute: typeof PrivateSellerProductsPreviewProductIdRoute
  PrivateSellerProductsCreateIndexRoute: typeof PrivateSellerProductsCreateIndexRoute
}

const PrivateSellerRouteRouteChildren: PrivateSellerRouteRouteChildren = {
  PrivateSellerInfoIndexRoute: PrivateSellerInfoIndexRoute,
  PrivateSellerProductsIndexRoute: PrivateSellerProductsIndexRoute,
  PrivateSellerProductsEditProductIdRoute:
    PrivateSellerProductsEditProductIdRoute,
  PrivateSellerProductsPreviewProductIdRoute:
    PrivateSellerProductsPreviewProductIdRoute,
  PrivateSellerProductsCreateIndexRoute: PrivateSellerProductsCreateIndexRoute,
}

const PrivateSellerRouteRouteWithChildren =
  PrivateSellerRouteRoute._addFileChildren(PrivateSellerRouteRouteChildren)

interface PrivateRouteRouteChildren {
  PrivateAdminRouteRoute: typeof PrivateAdminRouteRouteWithChildren
  PrivateBuyerRouteRoute: typeof PrivateBuyerRouteRouteWithChildren
  PrivateSellerRouteRoute: typeof PrivateSellerRouteRouteWithChildren
  PrivateAccountIndexRoute: typeof PrivateAccountIndexRoute
  PrivateAccountOrdersIndexRoute: typeof PrivateAccountOrdersIndexRoute
}

const PrivateRouteRouteChildren: PrivateRouteRouteChildren = {
  PrivateAdminRouteRoute: PrivateAdminRouteRouteWithChildren,
  PrivateBuyerRouteRoute: PrivateBuyerRouteRouteWithChildren,
  PrivateSellerRouteRoute: PrivateSellerRouteRouteWithChildren,
  PrivateAccountIndexRoute: PrivateAccountIndexRoute,
  PrivateAccountOrdersIndexRoute: PrivateAccountOrdersIndexRoute,
}

const PrivateRouteRouteWithChildren = PrivateRouteRoute._addFileChildren(
  PrivateRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicAuthRouteRoute: typeof PublicAuthRouteRoute
  PublicGoodbyeRouteRoute: typeof PublicGoodbyeRouteRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicSellerApplyIndexRoute: typeof PublicSellerApplyIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicAuthRouteRoute: PublicAuthRouteRoute,
  PublicGoodbyeRouteRoute: PublicGoodbyeRouteRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicSellerApplyIndexRoute: PublicSellerApplyIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  PrivateRouteRoute: PrivateRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAuthDeleteUserCallbackRoute: ApiAuthDeleteUserCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
