/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivateRouteRouteImport } from './routes/_private/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrivateUsersIndexRouteImport } from './routes/_private/users/index'
import { Route as PrivateProfileIndexRouteImport } from './routes/_private/profile/index'
import { Route as PrivateCategoriesIndexRouteImport } from './routes/_private/categories/index'
import { Route as AuthRegisterIndexRouteImport } from './routes/_auth/register/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'

const PrivateRouteRoute = PrivateRouteRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateUsersIndexRoute = PrivateUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateProfileIndexRoute = PrivateProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateCategoriesIndexRoute = PrivateCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const AuthRegisterIndexRoute = AuthRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginIndexRoute
  '/register': typeof AuthRegisterIndexRoute
  '/categories': typeof PrivateCategoriesIndexRoute
  '/profile': typeof PrivateProfileIndexRoute
  '/users': typeof PrivateUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginIndexRoute
  '/register': typeof AuthRegisterIndexRoute
  '/categories': typeof PrivateCategoriesIndexRoute
  '/profile': typeof PrivateProfileIndexRoute
  '/users': typeof PrivateUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_private': typeof PrivateRouteRouteWithChildren
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_auth/register/': typeof AuthRegisterIndexRoute
  '/_private/categories/': typeof PrivateCategoriesIndexRoute
  '/_private/profile/': typeof PrivateProfileIndexRoute
  '/_private/users/': typeof PrivateUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/categories'
    | '/profile'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/register' | '/categories' | '/profile' | '/users'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_private'
    | '/_auth/login/'
    | '/_auth/register/'
    | '/_private/categories/'
    | '/_private/profile/'
    | '/_private/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  PrivateRouteRoute: typeof PrivateRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/users/': {
      id: '/_private/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof PrivateUsersIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/profile/': {
      id: '/_private/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof PrivateProfileIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/categories/': {
      id: '/_private/categories/'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof PrivateCategoriesIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_auth/register/': {
      id: '/_auth/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface PrivateRouteRouteChildren {
  PrivateCategoriesIndexRoute: typeof PrivateCategoriesIndexRoute
  PrivateProfileIndexRoute: typeof PrivateProfileIndexRoute
  PrivateUsersIndexRoute: typeof PrivateUsersIndexRoute
}

const PrivateRouteRouteChildren: PrivateRouteRouteChildren = {
  PrivateCategoriesIndexRoute: PrivateCategoriesIndexRoute,
  PrivateProfileIndexRoute: PrivateProfileIndexRoute,
  PrivateUsersIndexRoute: PrivateUsersIndexRoute,
}

const PrivateRouteRouteWithChildren = PrivateRouteRoute._addFileChildren(
  PrivateRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  PrivateRouteRoute: PrivateRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
